### ISSUE TITLE
`load_model` function not defined

### ISSUE THREAD

**Issue by danieldeutsch** [recitalAI/QuestEval#2]
Hi,

I tried running your metric with the weighter, but there was a runtime error that the `self.load_model` function doesn't exist. Should it be `self.generic_load_model` instead?

https://github.com/recitalAI/QuestEval/blob/0e34be5d84c3329a012d6e31ffbec292d1f16573/questeval/questeval_metric.py#L173-L176

Thanks!

**Comment by ThomasScialom** [comment]
Hey Daniel, thank you for catching this! It should be fine now and the model available as well.
